import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {CONFIG} from '../src/config.js';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],failed=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});await fs.mkdir('artifacts/agenda',{recursive:true});
const settle=()=>p.waitForFunction(()=>{const d=document.querySelector('#invitation').dataset;return d.travelling==='false'&&['prologueBusy','courtyardBusy','welcomeBusy','clockBusy','mapBusy'].every(k=>d[k]!=='true');});const next=async()=>{await p.locator('#nav-next').click();await settle();};const back=async()=>{await p.locator('#nav-back').click();await settle();};
try{await p.goto('http://127.0.0.1:5173/');await p.waitForFunction(()=>document.querySelector('#app').dataset.ready==='true');for(let i=0;i<8;i++)await next();await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#nav-next').click();await p.waitForTimeout(2200);assert.equal(await p.locator('#nav-next').isDisabled(),true);const angle=await p.locator('.courtyard-left').evaluate(e=>Math.acos(new DOMMatrix(getComputedStyle(e).transform).m11)*180/Math.PI);assert.ok(angle>10&&angle<65,`slow partial angle ${angle}`);await p.screenshot({path:'artifacts/agenda/slow-gate.png'});await settle();assert.match(await p.locator('.courtyard-left').getAttribute('style'),/rotateY\(-82deg\)/);await next();
 const centered=await p.locator('#cover .vn-dialogue').evaluate(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return Math.abs(r.x+r.width/2-(p.x+p.width/2))<1&&Math.abs(r.y+r.height/2-(p.y+p.height/2))<1;});assert.ok(centered);assert.equal(await p.locator('.courtyard-wedding').evaluate(e=>getComputedStyle(e).color),'rgb(247, 217, 182)');await p.screenshot({path:'artifacts/agenda/title.png'});
 await p.emulateMedia({reducedMotion:'reduce'});while(await p.locator('#invitation').getAttribute('data-scene')!=='4')await next();await next();assert.equal(await p.locator('#location .vn-dialogue .maproom-venue').count(),0);assert.equal(await p.locator('#location > .maproom-venue').count(),1);assert.equal(await p.locator('.maproom-link').isVisible(),true);await p.screenshot({path:'artifacts/agenda/venue-panel.png'});await next();await next();await p.emulateMedia({reducedMotion:'no-preference'});await next();await p.screenshot({path:'artifacts/agenda/book.png'});await next();assert.equal(await p.locator('#invitation').getAttribute('data-scene'),'6');await back();
 await p.emulateMedia({reducedMotion:'reduce'});
 for(const[width,height]of [[360,640],[430,932],[1440,900],[844,390]]){await p.setViewportSize({width,height});
  for(let i=0;i<8;i++){if(i)await next();const s=p.locator(`#rundown-${i}`);assert.equal(await s.locator('.agenda-entry[aria-current] h3').textContent(),CONFIG.RUNDOWN[i][1]);assert.equal(await s.locator('.agenda-entry[aria-current] time').textContent(),CONFIG.RUNDOWN[i][0]+' WIB');const box=await s.locator('.vn-dialogue').boundingBox(),card=await s.locator('.agenda-card').boundingBox(),nav=await p.locator('.vn-bottom').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<nav.y);assert.ok(card.y+card.height<box.y||card.x+card.width<box.x,`card clear ${width} ${i} ${JSON.stringify({card,box})}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight),true);if(i===0||i===6)await p.screenshot({path:`artifacts/agenda/${width}-${i}.png`});}
  await next();assert.equal(await p.locator('#invitation').getAttribute('data-scene'),'13');await back();for(let i=0;i<7;i++)await back();
  await back();const v=await p.locator('.maproom-venue').boundingBox(),d=await p.locator('#location .vn-dialogue').boundingBox();assert.ok(v.y+v.height<d.y||v.x+v.width<d.x,`separate venue ${width}`);assert.equal(await p.locator('.maproom-venue').evaluate(e=>getComputedStyle(e).opacity),'1');await p.screenshot({path:`artifacts/agenda/venue-${width}.png`});await next();
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);const result={slowGate:true,noOverRotation:true,centeredTitle:true,creamHeading:true,separateVenuePanel:true,eightAgendaPages:true,originalSchedule:true,backReplay:true,fourViewports:true,errors,failed};await fs.writeFile('artifacts/agenda/results.json',JSON.stringify(result,null,2));console.log(result);
}finally{await b.close();}
