import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {setSession,session,canReadPhoto,equal,PHOTO,sameOrigin,sign} from '../server/album-core.js';
process.env.BLOB_READ_WRITE_TOKEN='test-only-secret-not-a-real-token';
test('Album session signatures reject tampering and expiry',()=>{let cookie;const s=setSession({setHeader:(_,v)=>cookie=v},{role:'guest',name:'Tamu'});assert.equal(session({headers:{cookie}}).owner,s.owner);assert.equal(session({headers:{cookie:cookie.replace('wedding_album=','wedding_album=x')}}),null);setSession({setHeader:(_,v)=>cookie=v},{role:'admin',owner:randomUUID(),expires:0});assert.equal(session({headers:{cookie}}).role,'admin');assert.equal(equal('é','aa'),false);assert.equal(session({headers:{cookie:'wedding_album=invalid.invalid'}}),null);});
test('Photos stay private until approved and revealed',()=>{const owner={role:'guest',owner:'a'},other={role:'guest',owner:'b'},admin={role:'admin',owner:'c'},photo={owner:'a',status:'pending'};assert.equal(canReadPhoto(null,photo,{revealed:true}),false);assert.equal(canReadPhoto(owner,photo,{revealed:false}),true);assert.equal(canReadPhoto(other,photo,{revealed:true}),false);assert.equal(canReadPhoto(admin,photo,{revealed:false}),true);photo.status='approved';assert.equal(canReadPhoto(other,photo,{revealed:false}),false);assert.equal(canReadPhoto(other,photo,{revealed:true}),true);photo.status='hidden';assert.equal(canReadPhoto(other,photo,{revealed:true}),false);});
test('Expired signed session is rejected',()=>{const data=Buffer.from(JSON.stringify({role:'admin',owner:randomUUID(),expires:Date.now()-1000})).toString('base64url');assert.equal(session({headers:{cookie:`wedding_album=${data}.${sign(data)}`}}),null);});
test('Upload paths and mutation origins are constrained',()=>{assert.ok(PHOTO.test(`photos/${randomUUID()}/${randomUUID()}.jpg`));assert.equal(PHOTO.test('../../album/settings.json'),false);assert.throws(()=>sameOrigin({headers:{origin:'https://evil.invalid',host:'wedding.test'}}));assert.doesNotThrow(()=>sameOrigin({headers:{origin:'https://wedding.test',host:'wedding.test'}}));});
