import test from 'node:test';
import assert from 'node:assert/strict';
import { createBackend } from './gas-harness.mjs';
test('Server validation rejects empty, short, invalid counts and honeypot',()=>{const b=createBackend();for(const [name,guests,website] of [['',1,''],['A',1,''],['Valid',0,''],['Valid',6,''],['Valid',1.5,''],['Valid','2',''],['Valid',2,'bot'],['x'.repeat(61),1,'']]){assert.equal(b.call({action:'reserve',name,guests,website}).ok,false);}assert.equal(b.data.length,1);});
test('Normalized names update an existing stable reservation ID',()=>{const b=createBackend();const one=b.call({action:'reserve',name:'  Ayu   Putri ',guests:2,website:''});const two=b.call({action:'reserve',name:'ayu putri',guests:5,website:''});assert.equal(one.ok,true);assert.match(one.reservation.id,/^[A-HJ-NP-Z2-9]{8}$/);assert.equal(two.updated,true);assert.equal(two.reservation.id,one.reservation.id);assert.equal(b.data.length,2);assert.equal(two.reservation.guests,5);assert.equal(b.metrics().lockCount,2);assert.equal(b.metrics().locked,false);});
test('Simultaneous caller harness retains both writes; every write is locked',async()=>{const b=createBackend();const results=await Promise.all(['Satu Tamu','Dua Tamu'].map(name=>Promise.resolve().then(()=>b.call({action:'reserve',name,guests:2,website:''}))));assert.ok(results.every(r=>r.ok));assert.equal(b.data.length,3);assert.equal(b.metrics().writeCount,2);assert.equal(b.metrics().lockCount,2);});
test('Admin requires PIN; check-in is idempotent and stats count guests',()=>{const b=createBackend();const created=b.call({action:'reserve',name:'Nadia Utami',guests:3,website:''});for(const action of ['list','stats','checkin'])assert.equal(b.call({action,pin:'wrong',id:created.reservation.id}).ok,false);const checked=b.call({action:'checkin',pin:'test-only-pin',id:'DJSL-'+created.reservation.id});assert.equal(checked.reservation.name,'Nadia Utami');assert.equal(checked.reservation.guests,3);assert.equal(checked.reservation.checked_in,true);const again=b.call({action:'checkin',pin:'test-only-pin',id:created.reservation.id});assert.equal(again.reservation.checked_in_at,checked.reservation.checked_in_at);const stats=b.call({action:'stats',pin:'test-only-pin'});assert.deepEqual(stats.stats,{reservations:1,guests:3,checkedIn:3});assert.equal(b.call({action:'checkin',pin:'test-only-pin',id:'invalid'}).ok,false);});
test('Malformed or unknown actions disclose no records',()=>{const b=createBackend();assert.equal(b.call({action:'delete'}).ok,false);assert.equal(b.call(null).ok,false);assert.equal(b.call({action:'reserve',name:'Line\nbreak',guests:1}).ok,false);});
test('Formula-like names and normalized keys stay literal and update correctly',()=>{const b=createBackend();for(const name of ['=1+1', '+Someone', "'Quoted"]){const first=b.call({action:'reserve',name,guests:1});const again=b.call({action:'reserve',name,guests:2});assert.equal(again.reservation.id,first.reservation.id);assert.equal(again.updated,true);}for(const row of b.data.slice(1)){assert.ok(row[3].startsWith("'"));assert.ok(row[4].startsWith("'"));}const list=b.call({action:'list',pin:'test-only-pin'});assert.deepEqual(list.reservations.map(x=>x.name),['=1+1','+Someone',"'Quoted"]);});
