import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createBackend } from './gas-harness.mjs';
import { CONFIG } from '../src/config.js';
const base='http://127.0.0.1:5173';
await fs.mkdir('artifacts/browser',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',acceptDownloads:true});
const errors=[],backend=createBackend();let failNetwork=false;
await context.route('**/src/config.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace("APPS_SCRIPT_URL: ''",`APPS_SCRIPT_URL: '${base}/__test-api'`)});});
await context.route('**/__test-api',async route=>{if(failNetwork)return route.abort('failed');await route.fulfill({contentType:'application/json',body:JSON.stringify(backend.call(route.request().postDataJSON()))});});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const ids=['gate','cover','greeting','countdown','location','rundown','dresscode','reservation','closing'];
const shots=[];
try {
for(const width of [360,390,430]){
 await page.setViewportSize({width,height:844});await page.goto(base);await page.waitForFunction(()=>document.querySelector('#app')?.dataset.ready==='true');await page.evaluate(()=>document.fonts.ready);
 for(const id of ids){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.locator('#'+id+' img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode().catch(()=>{});})));await page.waitForTimeout(80);await page.locator('#'+id).screenshot({path:`artifacts/browser/${width}-${id}.png`});shots.push(`${width}-${id}`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width} ${id}`);}
}
await page.goto(base+'/?to='+encodeURIComponent('  <b>Nama Tamu</b>  '));await page.waitForFunction(()=>document.querySelector('#app')?.dataset.ready==='true');assert.equal(await page.locator('#recipient').textContent(),'Untuk <b>Nama Tamu</b>');assert.equal(await page.locator('#recipient b').count(),0);assert.equal(await page.locator('#guest-name').inputValue(),'<b>Nama Tamu</b>');
await page.goto(base+'/?to='+encodeURIComponent('x'.repeat(80)));await page.waitForFunction(()=>document.querySelector('#app')?.dataset.ready==='true');assert.equal((await page.locator('#guest-name').inputValue()).length,60);
const name=page.locator('#guest-name'),count=page.locator('#guest-count'),submit=page.locator('#submit-reservation');
for(const [n,g,message] of [['',1,'Nama belum diisi'],['A',1,'Nama minimal 2 karakter'],['Nadia Utami',0,'Jumlah tamu minimal 1'],['Nadia Utami',6,'Jumlah tamu maksimal 5']]){await name.fill(n);await count.fill(String(g));await count.dispatchEvent('input');assert.equal(await submit.isDisabled(),true);assert.ok((await page.locator('#reservation-form').textContent()).includes(message));}
await name.fill('Nadia Utami');await count.fill('3');await submit.click();await page.waitForSelector('.ticket-code');
const firstId=await page.locator('.ticket-code').textContent();assert.match(firstId,/^DJSL-[A-HJ-NP-Z2-9]{8}$/);assert.equal(await page.locator('.ticket-name').textContent(),'Nadia Utami');assert.equal(await page.locator('.ticket-guests').textContent(),'3');
await page.locator('.ticket-qr').screenshot({path:'artifacts/browser/qr-debug.png'});
const decoded=await page.evaluate(async()=>{const img=document.querySelector('.ticket-qr');await img.decode();const {default:QrScanner}=await import('/node_modules/qr-scanner/qr-scanner.min.js');return (await QrScanner.scanImage(img.src,{returnDetailedScanResult:true})).data;});assert.equal(decoded,firstId);
await page.locator('#ticket-card').screenshot({path:'artifacts/browser/ticket.png'});
const pngPromise=page.waitForEvent('download');await page.locator('#save-ticket').click();const png=await pngPromise;await png.saveAs('artifacts/browser/ticket-download.png');
const icsPromise=page.waitForEvent('download');await page.locator('#calendar').click();const ics=await icsPromise;await ics.saveAs('artifacts/browser/invitation.ics');const calendar=await fs.readFile('artifacts/browser/invitation.ics','utf8');for(const value of ['DTSTART:20261031T023000Z','DTEND:20261031T064000Z','GEO:3.6875523;98.6558724','LOCATION:Lumbung Kuliner',`URL:${CONFIG.BASE_URL}`])assert.ok(calendar.replaceAll('\r\n ','').includes(value),value);
await page.locator('#edit-reservation').click();await name.fill(' nadia   utami ');await count.fill('4');await submit.click();await page.waitForFunction(()=>document.querySelector('.ticket-guests')?.textContent==='4');assert.equal(await page.locator('.ticket-code').textContent(),firstId);assert.equal(backend.data.length,2);
await page.reload();await page.locator('#recall-ticket').click();assert.equal(await page.locator('.ticket-code').textContent(),firstId);
await page.locator('#edit-reservation').click();failNetwork=true;await submit.click();await page.waitForFunction(()=>document.querySelector('#reservation-status').textContent==='Gagal mengirim. Periksa koneksi lalu coba lagi.');assert.equal(await submit.isDisabled(),false);failNetwork=false;
const times=await page.locator('.timeline time').allTextContents();assert.deepEqual(times,CONFIG.RUNDOWN.map(x=>x[0]));assert.equal(CONFIG.EVENT.start,'2026-10-31T09:30:00+07:00');
assert.equal(await page.evaluate(()=>document.querySelector('.cover-couple').style.transform),'');
const admin=await context.newPage();admin.on('pageerror',e=>errors.push(e.message));await admin.goto(base+'/admin');await admin.locator('#admin-pin').fill('wrong');await admin.locator('#admin-login button').click();await admin.waitForFunction(()=>document.querySelector('#admin-status').textContent==='PIN tidak valid.');await admin.locator('#admin-pin').fill('test-only-pin');await admin.locator('#admin-login button').click();await admin.waitForSelector('#admin-panel:visible');
const qrSource=await page.locator('.ticket-qr').getAttribute('src');await admin.bringToFront();await admin.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();const canvas=document.createElement('canvas');canvas.width=720;canvas.height=720;const g=canvas.getContext('2d');const draw=()=>{g.fillStyle='#EADFC8';g.fillRect(0,0,720,720);g.drawImage(img,110,110,500,500);};draw();setInterval(draw,200);navigator.mediaDevices.getUserMedia=async()=>canvas.captureStream(5);},qrSource);await admin.locator('#scan').click();await admin.waitForFunction(()=>document.querySelector('#checkin-result').textContent.includes('Jumlah Tamu: 4'));assert.equal(await admin.locator('svg').count(),0);
await admin.locator('#manual-code').fill(decoded);await admin.locator('#manual-form button').click();assert.ok((await admin.locator('#checkin-result').textContent()).includes('nadia   utami'));assert.ok((await admin.locator('#checkin-result').textContent()).includes('Jumlah Tamu: 4'));await admin.locator('#mark-present').click();await admin.waitForFunction(()=>document.querySelector('#total-checkin').textContent==='4');await admin.locator('#search-name').fill('nadia');assert.equal(await admin.locator('.admin-row').count(),1);await admin.screenshot({path:'artifacts/browser/admin.png',fullPage:true});
const csvPromise=admin.waitForEvent('download');await admin.locator('#export').click();const csv=await csvPromise;await csv.saveAs('artifacts/browser/reservasi.csv');assert.ok((await fs.readFile('artifacts/browser/reservasi.csv','utf8')).includes(firstId.slice(5)));
const simultaneous=await Promise.all(['Dina Lestari','Ari Wijaya'].map(n=>context.request.post(base+'/__unused').then(()=>backend.call({action:'reserve',name:n,guests:2}))));assert.ok(simultaneous.every(x=>x.ok));assert.equal(backend.data.length,4);
await page.bringToFront();await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base);await page.waitForFunction(()=>document.querySelector('#app')?.dataset.ready==='true');await page.waitForTimeout(800);await page.locator('#music-toggle').click();assert.equal(await page.locator('#music-toggle').getAttribute('aria-label'),'Matikan musik');await page.locator('#open-gate').click();await page.waitForFunction(()=>scrollY>100);assert.ok((await page.locator('.gate-left').getAttribute('style')).includes('rotateY'));
for(const row of await page.locator('.timeline-row').all()){await row.scrollIntoViewIfNeeded();await page.waitForTimeout(1100);assert.equal(await row.locator('.timeline-copy').evaluate(e=>getComputedStyle(e).opacity),'1');}
await page.locator('#rundown').screenshot({path:'artifacts/browser/rundown-motion.png'});
assert.deepEqual(errors,[]);const result={screenshots:shots.length,widths:[360,390,430],sections:ids,noHorizontalOverflow:true,validationCases:4,plainTextPersonalization:true,qrDecoded:decoded,ticketDownload:true,calendarDates:true,duplicateUpdate:true,ticketRecall:true,networkFailure:true,adminCheckin:true,simulatedCameraDecode:true,reducedMotion:true,gateAnimation:true,allTimelineRows:true,browserErrors:errors,backend:'Actual Code.gs executed with in-memory Google service adapters; live Google deployment not configured'};await fs.writeFile('artifacts/browser/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}
