import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createBackend} from './gas-harness.mjs';
const base='http://127.0.0.1:5173';const backend=createBackend();let session=null,uploadFailed=true;
await fs.mkdir('artifacts/companions',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('https://script.google.com/**',r=>r.fulfill({json:backend.call(r.request().postDataJSON())}));
await context.route('**/api/album',async r=>{const b=r.request().method()==='POST'?r.request().postDataJSON():{};if(b.type==='blob.generate-client-token')return r.fulfill({status:503,json:{error:'Simulated offline'}});if(b.action==='join')session={role:'guest',name:b.name,owner:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'};if(b.action==='login')session={role:'admin',name:'Panitia',owner:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'};if(b.action==='logout')session=null;if(b.action==='complete')return r.fulfill({status:400,json:{ok:false,error:'Belum terkirim'}});return r.fulfill({json:{ok:true,session,photos:[],revealed:false,uploadsOpen:true,eventKey:'test-album-key',cursor:null}});});
try{
 await page.goto(base+'/cetak');await page.waitForFunction(()=>document.querySelector('#app').dataset.ready==='true');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'artifacts/companions/print-desktop.png',fullPage:true});await page.pdf({path:'output/pdf/undangan-bifari-syafira-A5.pdf',preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false});
 await page.goto(base+'/reservasi?mode=panitia');await page.locator('#direct-name').fill('Keluarga Senja');await page.locator('#direct-guests').selectOption('3');await page.locator('#direct-submit').click();await page.waitForSelector('#direct-result:visible');assert.match(await page.locator('#direct-code').textContent(),/^\d{3} \d{3}$/);assert.equal(await page.locator('#a5-name').textContent(),'Keluarga Senja');const code=(await page.locator('#direct-code').textContent()).replace(' ','');
 await page.waitForFunction(()=>document.querySelector('#direct-status').textContent.startsWith('Reservasi tersimpan'));const decoded=await page.evaluate(async()=>{const img=document.querySelector('#a5-checkin');await img.decode();const {default:QrScanner}=await import('/node_modules/qr-scanner/qr-scanner.min.js');return (await QrScanner.scanImage(img.src,{returnDetailedScanResult:true})).data;});assert.equal(decoded,'DJSL-'+code);
 await page.pdf({path:'artifacts/companions/personalized-A5.pdf',preferCSSPageSize:true,printBackground:true});
 await page.goto(base+'/buku-tamu');await page.locator('#admin-pin').fill('test-only-pin');await page.locator('#admin-login button').click();await page.waitForSelector('#admin-panel:visible');await page.locator('#manual-code').fill(code);await page.locator('#manual-form button').click();await page.locator('#mark-present').click();await page.waitForFunction(()=>document.querySelector('#total-checkin').textContent==='3');await page.screenshot({path:'artifacts/companions/guestbook.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/reservasi');await page.waitForFunction(()=>document.querySelector('#app').dataset.ready==='true');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'artifacts/companions/reservation-mobile.png',fullPage:true});
 await page.goto(base+'/kamera#album=test-album-key');await page.locator('#camera-name').fill('Senja');await page.locator('#camera-login-form button').click();await page.waitForSelector('#camera-workspace:visible');await page.screenshot({path:'artifacts/companions/camera-mobile.png',fullPage:true});
 await page.locator('#photo-file').setInputFiles('public/assets/og-image.png');await page.waitForFunction(()=>document.querySelector('#camera-status').textContent.includes('antrean.'));assert.equal(await page.locator('.queue-item').count(),1);await page.reload();await page.waitForSelector('.queue-item');assert.equal(await page.locator('.queue-item').count(),1);
 await page.goto(base+'/album-admin');await page.locator('#camera-pin').fill('test-only-pin');await page.locator('#camera-login-form button').click();await page.waitForSelector('#album-qr[src]');assert.ok((await page.locator('#album-link').inputValue()).includes('/kamera#album=test-album-key'));await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'artifacts/companions/album-admin.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('Passed: direct reservation, personalized QR, guestbook check-in, mobile layout, upload failure queue persistence, admin QR, A5 PDF.');
}finally{await browser.close();}
