import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:360,height:640},reducedMotion:'reduce'}),errors=[];
p.on('pageerror',e=>errors.push(e.message));await p.route('**/src/invitation.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('const journey=initMotion();','const journey=initMotion();window.testJourney=journey;')});});
const go=async i=>p.evaluate(i=>window.testJourney.goTo(i),i);const next=async()=>p.evaluate(()=>window.testJourney.next());
try{await fs.mkdir('artifacts/finale',{recursive:true});await p.goto('http://127.0.0.1:5173');await p.waitForFunction(()=>window.testJourney);assert.equal(await p.locator('.arrival-card-small').count(),0);for(let i=0;i<6;i++)await next();await p.screenshot({path:'artifacts/finale/letter.png'});
 await go(1);await go(0);assert.match(await p.locator('.courtyard-left').getAttribute('style'),/rotateY\(-82deg\)/);assert.match(await p.locator('.courtyard-right').getAttribute('style'),/rotateY\(82deg\)/);
 for(const [width,height]of [[360,640],[430,932],[1440,900],[844,390]]){await p.setViewportSize({width,height});await go(2);await go(3);await next();await next();assert.equal(await p.locator('.event-date>*').count(),3);assert.ok(await p.locator('.venue-logo').evaluate(e=>parseFloat(getComputedStyle(e).borderRadius)>0));await p.screenshot({path:`artifacts/finale/clock-${width}.png`});
 for(const i of [5,7,12,13,14,15]){await go(i);if(i===13)await next();await p.screenshot({path:`artifacts/finale/${i}-${width}.png`});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight),true);assert.equal(await p.locator('.vn-scene:not([inert]) img').evaluateAll(a=>a.every(x=>x.complete&&x.naturalWidth>0)),true);if(i>=5&&i<=12){const row=p.locator('.vn-scene:not([inert]) .agenda-entry[aria-current]');assert.equal(await row.count(),1);const r=await row.boundingBox(),c=await p.locator('.vn-scene:not([inert]) .agenda-card').boundingBox();assert.ok(r.y>=c.y-1&&r.y+r.height<=c.y+c.height+1);}}
 await p.locator('#nav-back').click();await p.waitForFunction(()=>document.querySelector('#invitation').dataset.travelling==='false');assert.equal(await p.locator('#invitation').getAttribute('data-scene'),'14');}
 await p.emulateMedia({reducedMotion:'no-preference'});await go(13);await go(14);await go(15);assert.deepEqual(errors,[]);console.log('Finale: outward gate, 3-line date/logo, progressive scroll, dresscode, reservation and closing, 4 viewports, normal transitions: passed.');
}finally{await b.close();}
