import {createHmac,timingSafeEqual,randomUUID} from 'node:crypto';
import {get,put,head,list} from '@vercel/blob';
import {CONFIG} from '../src/config.js';
export const UUID='[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
export const PHOTO=new RegExp(`^photos/(${UUID})/(${UUID})\\.jpg$`);
export const PHOTO_ID=new RegExp(`^${UUID}$`);
export function sign(value){if(!process.env.BLOB_READ_WRITE_TOKEN)throw new Error('Penyimpanan belum tersedia.');return createHmac('sha256',process.env.BLOB_READ_WRITE_TOKEN).update('wedding-album-v1:'+value).digest('base64url');}
export function equal(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
export const eventKey=()=>sign('guest-event-link');
export function session(req){try{const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('wedding_album='))?.slice(14);if(!cookie)return null;const [data,mac]=cookie.split('.');if(!equal(mac,sign(data)))return null;const value=JSON.parse(Buffer.from(data,'base64url').toString());if(!Number.isFinite(value.expires)||value.expires<Date.now()||!['guest','admin'].includes(value.role)||!PHOTO_ID.test(value.owner))return null;return value;}catch{return null;}}
export function setSession(res,value){const maxAge=value.role==='admin'?28800:2592000;const payload={...value,owner:value.owner||randomUUID(),expires:Date.now()+maxAge*1000};const data=Buffer.from(JSON.stringify(payload)).toString('base64url');res.setHeader('Set-Cookie',`wedding_album=${data}.${sign(data)}; HttpOnly; Secure; SameSite=Lax; Path=/api; Max-Age=${maxAge}`);return payload;}
export function requireSession(req,admin=false){const s=session(req);if(!s||(admin&&s.role!=='admin'))throw Object.assign(new Error('Silakan masuk kembali.'),{status:401});return s;}
export function sameOrigin(req){if(req.headers.origin&&req.headers.origin!==`https://${req.headers.host}`&&req.headers.origin!==`http://${req.headers.host}`)throw Object.assign(new Error('Asal permintaan tidak valid.'),{status:403});}
export async function readJson(path,fallback=null){try{const r=await get(path,{access:'private',useCache:false});if(!r)return fallback;return JSON.parse(await new Response(r.stream).text());}catch(e){if(e.name==='BlobNotFoundError')return fallback;throw e;}}
export async function writeJson(path,value,overwrite=true){return put(path,JSON.stringify(value),{access:'private',addRandomSuffix:false,allowOverwrite:overwrite,contentType:'application/json',cacheControlMaxAge:0});}
export const settings=()=>readJson('album/settings.json',{revealed:false,uploadsOpen:true});
export function canReadPhoto(s,m,state){return !!s&&!!m&&(s.role==='admin'||s.owner===m.owner||(state.revealed&&m.status==='approved'));}
export async function finishPhoto(path,name){const match=PHOTO.exec(path);if(!match)throw new Error('Foto tidak valid.');const [,owner,id]=match;const metadata=await head(path);if(metadata.contentType!=='image/jpeg'||metadata.size>8*1024*1024)throw new Error('Berkas foto tidak valid.');const record={id,owner,path,name:String(name||'Tamu').slice(0,60),status:'pending',createdAt:new Date().toISOString(),size:metadata.size};try{await writeJson(`meta/${id}.json`,record,false);}catch(e){if(e.name!=='BlobPreconditionFailedError'&&!/already exists/i.test(e.message))throw e;}return {ok:true,id};}
export async function verifyPin(pin){if(typeof pin!=='string'||pin.length>128||!pin)throw Object.assign(new Error('PIN tidak valid.'),{status:401});const r=await fetch(CONFIG.APPS_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'stats',pin}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error('Tidak dapat menghubungi reservasi.');const result=await r.json();if(!result.ok)throw Object.assign(new Error(result.error||'PIN tidak valid.'),{status:401});}
export async function getPhotos(cursor){const result=await list({prefix:'meta/',limit:36,...(cursor?{cursor}: {})});const records=await Promise.all(result.blobs.map(x=>readJson(x.pathname)));return {records:records.filter(Boolean),cursor:result.hasMore?result.cursor:null};}
