import { request, ID_PATTERN, normalizeCode, displayCode } from './api.js';
import { icon } from './art.js';
import { downloadBlob } from './ticket.js';
export async function renderAdmin(app){
 let pin='',rows=[],scanner=null,selected=null,busy=false;
 app.innerHTML=`<main class="admin paper"><a href="/" class="admin-back">← Undangan Pernikahan</a><h1>Daftar Reservasi</h1><form id="admin-login"><label for="admin-pin">PIN</label><input type="password" id="admin-pin" autocomplete="current-password" required/><button class="button primary">Masuk</button></form><p id="admin-status" role="status" aria-live="polite"></p><div id="admin-panel" hidden><div class="admin-totals"><div><span>Total Tamu</span><strong id="total-guests">0</strong></div><div><span>Check-in</span><strong id="total-checkin">0</strong></div></div><div class="admin-actions"><button class="button" id="refresh">Muat Ulang</button><button class="button" id="export">${icon('download')}Ekspor CSV</button><button class="button" id="logout">Keluar</button></div><section class="checkin-box"><h2>Check-in</h2><div class="scan-actions"><button class="button primary" id="scan">Pindai QR</button><button class="button" id="stop-scan" hidden>Tutup kamera</button></div><div class="scanner-stage"><video id="scanner-video" playsinline muted hidden></video><div id="scanner-overlay" aria-hidden="true"><img src="/assets/png/scanner-frame.png" alt=""/></div></div><form id="manual-form"><label for="manual-code">Masukkan kode manual</label><div class="inline-form"><input id="manual-code" autocomplete="off" spellcheck="false" placeholder="482 731" inputmode="text" maxlength="18"/><button class="button">Cari</button></div></form><div id="checkin-result" aria-live="polite"></div></section><label for="search-name">Cari nama</label><input id="search-name" type="search" autocomplete="off"/><p id="list-note"></p><div id="reservation-list"></div></div></main>`;
 const $=s=>document.querySelector(s),status=$('#admin-status'),panel=$('#admin-panel');
 function safe(tag,text,cls=''){const node=document.createElement(tag);node.textContent=text;if(cls)node.className=cls;return node;}
 function render(){
   $('#total-guests').textContent=rows.reduce((s,r)=>s+r.guests,0);$('#total-checkin').textContent=rows.filter(r=>r.checked_in).reduce((s,r)=>s+r.guests,0);
   const query=$('#search-name').value.trim().toLowerCase(),filtered=rows.filter(r=>r.name.toLowerCase().includes(query)||r.id.toLowerCase().includes(query));
   const list=$('#reservation-list');list.replaceChildren();$('#list-note').textContent=`${filtered.length} reservasi`;
   for(const row of filtered){const item=safe('article','', 'admin-row'),details=safe('div','');details.append(safe('h3',row.name),safe('p',`${row.guests} tamu · ${displayCode(row.id)}`));const button=safe('button',row.checked_in?'Sudah hadir':'Check-in','button');button.type='button';button.onclick=()=>show(row);item.append(details,button);list.append(item);}
 }
 async function load(){if(busy)return;busy=true;$('#refresh').disabled=true;status.textContent='Memuat…';try{const result=await request('list',{pin});rows=result.reservations.map(r=>({...r,guests:Number(r.guests)}));panel.hidden=false;$('#admin-login').hidden=true;status.textContent='';render();}catch(error){status.textContent=rows.length?'Koneksi terputus. Daftar yang sudah dimuat tetap dapat dicari.':error.message;throw error;}finally{busy=false;$('#refresh').disabled=false;}}
 $('#admin-login').onsubmit=async event=>{event.preventDefault();pin=$('#admin-pin').value;try{await load();$('#admin-pin').value='';}catch{pin='';}};
 $('#refresh').onclick=()=>load().catch(()=>{});$('#search-name').oninput=render;
 function stop(){if(scanner)scanner.stop();$('#scanner-video').hidden=true;$('#stop-scan').hidden=true;$('#scan').hidden=false;}
 function show(row){selected=row;stop();const target=$('#checkin-result');target.replaceChildren();target.append(safe('h3',row.name),safe('p',`Jumlah Tamu: ${row.guests}`),safe('p',`${displayCode(row.id)}`));if(row.checked_in){target.append(safe('p','Sudah hadir','present'));return;}const button=safe('button','Tandai Hadir','button primary');button.id='mark-present';button.onclick=async()=>{button.disabled=true;status.textContent='Mengirim…';try{const result=await request('checkin',{id:row.id,pin});rows=rows.map(r=>r.id===row.id?result.reservation:r);show(result.reservation);render();status.textContent='Sudah hadir';}catch{status.textContent='Gagal mengirim. Periksa koneksi lalu coba lagi.';button.disabled=false;}};target.append(button);}
 function findCode(value){const id=normalizeCode(value);const row=ID_PATTERN.test(id)&&rows.find(r=>r.id===id);if(row){status.textContent='';show(row);}else{$('#checkin-result').textContent='Kode tidak ditemukan.';}return !!row;}
 $('#manual-form').onsubmit=event=>{event.preventDefault();findCode($('#manual-code').value);};
 $('#scan').onclick=async()=>{try{const {default:QrScanner}=await import('qr-scanner');if(!scanner)scanner=new QrScanner($('#scanner-video'),result=>findCode(result.data),{preferredCamera:'environment',returnDetailedScanResult:true,highlightScanRegion:true,overlay:$('#scanner-overlay'),maxScansPerSecond:5});$('#scanner-video').hidden=false;$('#stop-scan').hidden=false;$('#scan').hidden=true;await scanner.start();status.textContent='';}catch{stop();status.textContent='Kamera tidak tersedia. Masukkan kode manual atau cari nama.';}};
 $('#stop-scan').onclick=stop;
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',()=>scanner?.destroy());
 $('#export').onclick=()=>{const cell=value=>'"'+String(value).replace(/^[=+\-@]/,"'$&").replaceAll('"','""')+'"';const lines=[['id','name','guests','checked_in','checked_in_at'],...rows.map(r=>[r.id,r.name,r.guests,r.checked_in,r.checked_in_at])];downloadBlob(new Blob(['\uFEFF'+lines.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'reservasi.csv');};
 $('#logout').onclick=()=>{pin='';rows=[];selected=null;stop();scanner?.destroy();scanner=null;panel.hidden=true;$('#admin-login').hidden=false;$('#reservation-list').replaceChildren();$('#checkin-result').replaceChildren();$('#search-name').value='';status.textContent='';};
}
