import { CONFIG } from './config.js';
import { art, icon } from './art.js';
export function invitationMarkup(){
 const e=CONFIG.EVENT;
 return `<button class="music-toggle" id="music-toggle" aria-label="Nyalakan musik">${icon('music-off')}</button><main id="invitation">
 <section id="gate" class="scene dark gate-scene" aria-labelledby="gate-copy">
 <img class="gate-environment" src="/assets/png/gate-environment.png" alt="" width="760" height="1140" fetchpriority="high"/>
 <div class="gate-top"><span class="tiny">31 . 10 . 2026</span><span aria-hidden="true">✦</span><span class="tiny">B & S</span></div>
 <p id="gate-copy" class="gate-copy">Sebuah undangan menunggu<br>di balik gerbang.</p><p id="recipient" class="recipient" hidden></p>
 <div class="gate-stage"><div class="gate-leaf gate-left" data-layer="gate-left"><img src="/assets/png/gate.png" alt="" width="700" height="1050"/></div><div class="gate-leaf gate-right" data-layer="gate-right"><img src="/assets/png/gate.png" alt="" width="700" height="1050"/></div>${art('chains','gate-chain','chain')}${art('lantern','gate-lantern','lantern-body')}${art('raven','gate-raven','raven-head')}<div class="light-bloom" data-layer="glow"></div><div class="fog fog-one"></div><div class="fog fog-two"></div></div>
 <button id="open-gate" class="button primary">Buka Gerbang <span aria-hidden="true">↗</span></button><div class="gate-bottom" aria-hidden="true"><span></span>✦<span></span></div></section>
 <section id="cover" class="scene paper cover-scene" aria-labelledby="cover-title">${art('ornament-corner','corner top-left')}${art('ornament-corner','corner top-right')}<p class="eyebrow">Dua Jiwa, Satu Lentera</p><div class="cover-portrait">${art('arch-roses','cover-couple')}${art('petal','cover-petal')}</div><h1 id="cover-title"><span>Achmad Bifari</span><em>&</em><span>Syafira Aulia</span></h1>${art('ornament-divider','divider')}<p class="cover-date">${e.dateLabel}</p>${art('wax-seal','cover-seal')}${art('bat','cover-bat')}<div class="page-number" aria-hidden="true">I</div></section>
 <section id="greeting" class="scene paper greeting-scene" aria-label="Salam">${art('key','greeting-key')}<p class="greeting-copy">Di antara gelap dan cahaya, kami memilih saling menemukan. Dengan hangat, kami mengundangmu menyaksikan hari kami.</p>${art('ornament-divider','divider')}${art('rose-wilted','greeting-rose')}<div class="page-number" aria-hidden="true">II</div></section>
 <section id="countdown" class="scene dark countdown-scene" aria-labelledby="countdown-title"><h2 id="countdown-title">Menuju Hari Kami</h2><div class="clock-stage">${art('clock','clock-art','face')}${art('pendulum','clock-pendulum','pendulum')}</div><div id="countdown-digits" class="countdown-grid" role="timer" aria-label="Hitung mundur menuju 31 Oktober 2026 pukul 09:30 WIB">${['Hari','Jam','Menit','Detik'].map((l,i)=>`<div><span class="digit" data-digit="${i}">00</span><span class="digit-label">${l}</span></div>`).join('')}</div><p id="countdown-arrived" hidden>Hari yang dinanti telah tiba.</p><span class="little-ornament" aria-hidden="true">✦</span></section>
 <section id="location" class="scene paper location-scene" aria-labelledby="location-title"><h2 id="location-title">Lokasi</h2><h3 class="venue-name">${e.venue}</h3><div class="map-stage">${art('map-card','map-art')}<div class="route-reveal" data-layer="route-path"></div>${art('icon-pin','map-pin','pin')}</div><p>Tamu diminta hadir mulai pukul 09:30 WIB.</p><a class="button primary" href="${e.maps}" target="_blank" rel="noopener noreferrer">${icon('pin')}Buka di Google Maps</a><div class="page-number" aria-hidden="true">IV</div></section>
 <section id="rundown" class="scene paper rundown-scene" aria-labelledby="rundown-title"><h2 id="rundown-title">Rangkaian Acara</h2>${art('ornament-divider','divider')}<ol class="timeline">${CONFIG.RUNDOWN.map(([time,title,note,asset,extra])=>`<li class="timeline-row"><div class="timeline-rule"></div><span class="timeline-dot" aria-hidden="true">✦</span><div class="timeline-copy"><time>${time}</time><h3>${title}</h3><p>${note}</p></div><div class="timeline-art">${art(asset,`rundown-${asset}`)}${extra?art(extra,`rundown-extra extra-${extra}`):''}</div></li>`).join('')}</ol>${art('candle','timeline-candle','wax-drip')}<div class="page-number" aria-hidden="true">V</div></section>
 <section id="dresscode" class="scene dark dresscode-scene" aria-labelledby="dresscode-title"><h2 id="dresscode-title">Dresscode & Tema</h2><button class="swatch-button" id="swatch" aria-label="Kenakan warna maroon." aria-pressed="false">${art('cloth-swatch','cloth-art','cloth')}</button><p class="dresscode-lead">Kenakan warna maroon.</p><p>Dekorasi bernuansa gothic: remang, hangat, sedikit misterius.</p>${art('rose-wilted','dresscode-rose')}${art('petal','falling-petal','petal-1')}</section>
 <section id="reservation" class="scene paper reservation-scene" aria-labelledby="reservation-title">${art('lantern','reservation-lantern')}<h2 id="reservation-title">Reservasi</h2><p class="reservation-intro">Bantu kami menyiapkan kursimu. Isi nama dan jumlah tamu untuk melanjutkan.</p>
 <form id="reservation-form" novalidate><div class="form-field"><label for="guest-name">Nama tamu</label><input id="guest-name" name="name" type="text" required minlength="2" maxlength="60" autocomplete="name" aria-describedby="name-error"/><p class="field-error" id="name-error" aria-live="polite"></p></div><div class="form-field"><label for="guest-count">Jumlah tamu (termasuk kamu)</label><div class="stepper"><button type="button" id="minus" aria-label="Kurangi jumlah tamu">${icon('minus')}</button><input id="guest-count" name="guests" type="number" min="1" max="${CONFIG.MAX_GUESTS}" step="1" value="1" required inputmode="numeric" aria-describedby="count-error"/><button type="button" id="plus" aria-label="Tambah jumlah tamu">${icon('plus')}</button></div><p class="field-error" id="count-error" aria-live="polite"></p></div><div class="honeypot" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"/></div><button type="submit" class="button primary" id="submit-reservation" disabled>Kirim Reservasi <span aria-hidden="true">↗</span></button></form>
 <p id="reservation-status" role="status" aria-live="polite"></p><button class="button" id="recall-ticket" hidden>Lihat Tiket</button><div id="ticket-host" hidden></div><div class="reservation-petals" aria-hidden="true">${art('petal','stamp-petal p1')}${art('petal','stamp-petal p2')}${art('petal','stamp-petal p3')}</div><div class="page-number" aria-hidden="true">VII</div></section>
 <section id="closing" class="scene dark closing-scene" aria-label="Terima kasih">${art('bare-tree','closing-tree')}<div class="closing-stars" aria-hidden="true">${Array.from({length:6},(_,i)=>art('stars','closing-star star-'+i,'stars-'+i)).join('')}</div>${art('moon','closing-moon')}${art('lantern','closing-lantern')}<p class="closing-copy">Terima kasih sudah menyalakan lentera bersama kami.</p><button class="button" id="share">${icon('share')}Bagikan</button><button class="text-button" id="closing-music">Nyalakan musik</button><p id="share-status" role="status"></p>${art('raven-flight','closing-raven','raven-wing')}<p class="closing-monogram" aria-hidden="true">B <em>&</em> S</p><p class="tiny">31 . 10 . 2026</p></section>
 </main><a class="button primary sticky-reserve" href="#reservation" hidden>Reservasi <span aria-hidden="true">↗</span></a>`;
}
